from typing import Protocol


class Logger(Protocol):
    """The single logging interface every Heimei manager codes against.

    Structured logging only — every call takes a message and arbitrary
    keyword fields, never a pre-formatted string. See ADR-0012.
    """

    def debug(self, message: str, **fields: object) -> None: ...
    def info(self, message: str, **fields: object) -> None: ...
    def warning(self, message: str, **fields: object) -> None: ...
    def error(self, message: str, **fields: object) -> None: ...
    def critical(self, message: str, **fields: object) -> None: ...
